apiVersion: v1
kind: Service
metadata:
  name: coreappwithdocker 
  labels:
    app: coreappwithdocker 
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 80
    protocol: TCP
  selector:
    app: coreappwithdocker